# trading_bot/config/biased_MA_cross_config.yaml
# Biased Moving Average Crossover Strategy Configuration

# Exchange configuration
exchange:
  id: bybit # CCXT exchange ID
# api_key: YOUR_BYBIT_API_KEY (REMOVED - Use environment variables)
# secret: YOUR_BYBIT_SECRET (REMOVED - Use environment variables)
  params: {} # Optional exchange-specific parameters

# Trading parameters
trading:
  enabled: true
  symbols:
    - symbol: ETH/USDT
      market_type: spot
    - symbol: ENA/USDT
      market_type: spot
    - symbol: BLAST/USDT
      market_type: spot
    - symbol: EIGEN/USDT
      market_type: spot
    - symbol: MNT/USDT
      market_type: spot
  timeframe: 1m

# Strategy configuration
strategy:
  type: biased_spot_ma_crossover
  params:
    buy_short_period: 10
    buy_long_period: 30
    sell_short_period: 50
    sell_long_period: 200

# System settings
system:
  loop_interval: 60
  log_level: INFO
  log_file: logs/biased_spot_trading.log
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

risk:
  max_drawdown: 0.02  # Maximum allowed drawdown (2%)
  drawdown_check_interval: 300  # Check every 5 minutes (300 seconds)