# trading_bot/config/spot_config.yaml
# Spot-only trading bot configuration

# Exchange configuration
exchange:
  id: binance # Example for Binance, change if needed
# api_key: YOUR_BINANCE_API_KEY (REMOVED - Use environment variables)
# secret: YOUR_BINANCE_SECRET (REMOVED - Use environment variables)
  params: {} # Optional exchange-specific parameters

# Trading parameters
trading:
  enabled: true  # Set to false for initial testing
  symbols:
    - symbol: ETH/USDT
      market_type: spot
    - symbol: BTC/USDT
      market_type: spot
    - symbol: SOL/USDT
      market_type: spot
    - symbol: BLAST/USDT
      market_type: spot
    - symbol: COOK/USDT
      market_type: spot 
  timeframe: 1m
  
# Strategy configuration (fallback if symbol-specific strategy not defined)
strategy:
  type: moving_average_crossover_spot
  params:
    short_period: 20
    long_period: 50

# Risk management
# Position sizing is automatically calculated using equal division based on total number of trading pairs
risk:
  max_open_trades: 5  # Should match the number of trading pairs

# System settings
system:
  loop_interval: 60  # Seconds between iterations
  log_level: INFO
  log_file: logs/spot_trading.log  # Path to log file
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # Log format