# trading_bot/config/spot_config.yaml
# Spot-only trading bot configuration

# Exchange settings
exchange:
  id: bybit  # Exchange ID (binance, coinbase, etc.)
  api_key: "hG1MT0tQlGIvLCOx1R"  # API key (fill in your own)
  secret: "Ho7rwpJqdVfcOqbt7bEm3fIp6lww3NCBkJ4l"   # API secret (fill in your own)
  params:
    enableRateLimit: true

# Trading parameters
trading:
  enabled: true  # Set to false for initial testing
  symbols:
    - symbol: ETH/USDT
      market_type: spot
    - symbol: BTC/USDT
      market_type: spot
  timeframe: 1m
  
# Strategy configuration (fallback if symbol-specific strategy not defined)
strategy:
  type: moving_average_crossover_spot
  params:
    short_period: 20
    long_period: 50

# Risk management
risk:
  max_open_trades: 1
  risk_per_trade: 0.5  # 1% of portfolio per trade - conservative for testing
  stop_loss_pct: 0.05   # 5% stop loss

# System settings
system:
  loop_interval: 60  # Seconds between iterations
  log_level: INFO
  log_file: logs/spot_trading.log  # Path to log file
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # Log format